# Add 'repo' label to any root file changes
repo:
  - ./*

# Add 'test' label to any change to testing files
test:
  - tests/**/*.php

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - any: ['src/**/*', '!src/docs/*']
