version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: autowire
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - autowire

networks:
  autowire:
    driver: bridge